#pragma once

#include <Abstract/TechnoTypeClass.h>

// ============================================================================
// BuildingTypeClass - type definition for buildings
// ============================================================================
class NOVTABLE BuildingTypeClass : public TechnoTypeClass {
public:
    static const AbstractType AbsID = AbstractType::BuildingType;
    static DynamicVectorClass<BuildingTypeClass*>* Array;

    // Static lookup
    static BuildingTypeClass* Find(const char* pID);
    static BuildingTypeClass* FindByIndex(int32 index);
    static int32 GetCount();
    static void Init_Array();
    static void Delete_Array();
    static void Delete_All();

    virtual ~BuildingTypeClass();
    virtual bool LoadFromINI(CCINIClass* pINI) override;
    virtual bool SaveToINI(CCINIClass* pINI) const override;
    virtual AbstractType GetAbstractDerivationID() const override;
    virtual bool HasThisID(const char* pID) const override;
    virtual int32 GetCRC() const override;
    virtual int32 Size() const override;
    virtual AbstractType GetClassID() const override;
    virtual const char* get_ID() const override;
    virtual const wchar_t* GetUIName() const override;
    virtual void ComputeCRC(CRCEngine& crc) const override;

    // Building-specific helpers
    virtual bool IsUndeployable() const;
    virtual bool CanBeSold() const;
    virtual bool CanBeRepaired() const;
    virtual bool IsSimpleDeployer() const;
    virtual bool IsFirebase() const;
    virtual bool IsFactory() const;
    virtual bool IsPowerPlant() const;
    virtual bool IsWall() const;
    virtual bool IsTiberiumStorage() const;

    int32 Get_Width() const;
    int32 Get_Height() const;
    RectangleStruct Get_Occupy_Rect() const;
    int32 Get_Power_Output() const;
    int32 Get_Power_Drain() const;
    int32 Get_Storage_Capacity() const;
    AbstractType Get_Factory_Type() const;
    int32 Find_Exit_Cell(const CoordStruct& baseCoord) const;

    BuildingTypeClass() noexcept;
    explicit BuildingTypeClass(noinit_t) noexcept : TechnoTypeClass(noinit) {}

public:
    int32       BuildingFoundation; // Foundation width/height
    int32       Height;
    int32       Power;
    int32       PowerDrain;
    int32       Bib;
    bool        CanBeSold_;
    bool        IsUndeployable_;
    bool        IsSimpleDeployer_;
    bool        IsFirebase_;
    bool        IsFactory_;
    bool        HasSpotlight;
    bool        HasBib;
    bool        HasHelipad;
    bool        HasDock;
    bool        IsBase;
    bool        IsGate;
    bool        IsOreRefinery;
    bool        IsOreStorage;
    bool        IsWeaponsFactory;
    bool        IsBarracks;
    bool        IsRadar;
    bool        IsTech;
    bool        IsSecretLab;
    bool        IsConstructionYard;
    bool        IsAirport;
    bool        IsWarfactory;
    bool        IsNavalYard;
    bool        IsRepairPad;
    bool        IsMissileSilo;
    bool        IsPowered;
    bool        IsCanC4;
    bool        IsCanBeOccupied;
    bool        IsCanBeDriven;
    bool        IsCanBeCaptured;
    bool        IsCanBeRepaired_;
    bool        IsCanBeSold_;
    bool        IsCanBePowered;
    bool        IsCanBeDestroyed;
    bool        IsCanBeDamaged;
    bool        IsCanBeInfiltrated;
    bool        IsCanBeSpied;
    bool        IsCanBeSabotaged;
    bool        IsCanBeStolen;
    bool        IsCanBeHijacked;
    int32       Storage;
    int32       BuildingAnimCount;
    int32       OccupyCount;
    int32       NumberOfDocks;
    int32       Adjacent;
    int32       MaxWalls;
    int32       SuperWeapon;
    int32       SuperWeapon2;
    int32       WeaponCount;
    WeaponStruct Weapons[2];
    int32       OccupyWeaponCount;
    WeaponStruct OccupyWeapons[2];
    int32       EliteOccupyWeaponCount;
    WeaponStruct EliteOccupyWeapons[2];
    bool        HasSuperWeapon;
    bool        HasSuperWeapon2;
    bool        IsPlug;
    bool        IsDrain;
    bool        IsDrainable;
    bool        IsRig;
    bool        IsRigOwner;
    bool        IsResource;
    bool        IsResourceGatherer;
    bool        IsBombable;
    bool        IsAutoFire;
    bool        IsGuardRange;
    bool        IsAggressive;
    bool        IsUndeployableMember;
    bool        IsSellable;
    bool        IsRepairable;
    bool        IsUnsellable;
    bool        IsUngarrisonable;
    bool        IsNaval;
    bool        IsLand;
    bool        IsAir;
    bool        IsOrganic;
    bool        IsNeutral;
    bool        IsInfiltratable;
    bool        IsStealthy;
    bool        IsHealable;
    bool        IsTilter;
    bool        IsToProtect;
    bool        IsNominal;
    bool        IsRadarInvisible;
    bool        IsDontScore;
    bool        IsNoThreat;
    bool        IsSensorsSight;
    bool        IsHunterSeeker;
    bool        IsIvan;
    bool        IsLeader;
    bool        IsCarryall;
    bool        IsTrain;
    bool        IsConsideredAircraft;
    bool        IsConsideredVehicle;
    bool        IsPowered_;
    bool        IsScanner;
    bool        IsSensor;
    bool        IsDetector;
    bool        IsSensors;
    bool        IsPreventAttackMove;
    bool        IsNaval_;
    bool        IsLand_;
    bool        IsAir_;
    bool        IsOrganic_;
    bool        IsNeutral_;
    bool        IsInfiltratable_;
    bool        IsStealthy_;
    bool        IsHealable_;
    bool        IsTilter_;
    bool        IsToProtect_;
    bool        IsNominal_;
    bool        IsRadarInvisible_;
    bool        IsDontScore_;
    bool        IsNoThreat_;
    bool        IsSensorsSight_;
    bool        IsHunterSeeker_;
    bool        IsIvan_;
    bool        IsLeader_;
    bool        IsDock;
    bool        IsHelipad;
    bool        IsHasBib;
    bool        IsHasSpotlight;
    bool        IsBase_;
    bool        IsWall_;
    bool        IsGate_;
    bool        IsOreRefinery_;
    bool        IsOreStorage_;
    bool        IsWeaponsFactory_;
    bool        IsBarracks_;
    bool        IsRadar_;
    bool        IsTech_;
    bool        IsSecretLab_;
    bool        IsConstructionYard_;
    bool        IsAirport_;
    bool        IsWarfactory_;
    bool        IsNavalYard_;
    bool        IsRepairPad_;
    bool        IsMissileSilo_;
    bool        IsPlug_;
    bool        IsDrain_;
    bool        IsDrainable_;
    bool        IsRig_;
    bool        IsRigOwner_;
    bool        IsResource_;
    bool        IsResourceGatherer_;
    bool        IsBombable_;
    bool        IsAutoFire_;
    bool        IsGuardRange_;
    bool        IsAggressive_;
    bool        IsUndeployable__;
    bool        IsSellable_;
    bool        IsRepairable_;
    bool        IsUnsellable_;
    bool        IsUngarrisonable_;
    float       ThreatPosedValue_;
    int32       DeathWeaponIndex_;
    int32       BuildingAnimCount_;
    int32       OccupyCount_;
    int32       NumberOfDocks_;
    int32       Adjacent_;
    int32       MaxWalls_;
    bool        IsPowered2;
    bool        IsPlug2;
    bool        IsDrain2;
    bool        IsDrainable2;
    bool        IsRig2;
    bool        IsRigOwner2;
    bool        IsResource2;
    bool        IsResourceGatherer2;
    BYTE        padding_BuildingType[4];
};
