#pragma once

#include <Abstract/TechnoTypeClass.h>

class IsometricTileType;

// ============================================================================
// BuildingTypeClass - type definition for buildings
// ============================================================================
class NOVTABLE BuildingTypeClass : public TechnoTypeClass {
public:
    static const AbstractType AbsID = AbstractType::BuildingType;
    static DynamicVectorClass<BuildingTypeClass*>* Array;

    // Static lookup
    static BuildingTypeClass* Find(const char* pID);
    static BuildingTypeClass* FindOrAllocate(const char* pID);
    static BuildingTypeClass* FindByIndex(int32 index);
    static int32 FindIndex(const char* pID);
    static int32 GetCount();
    static void Init_Array();
    static void Delete_Array();
    static void Delete_All();

    virtual ~BuildingTypeClass();
    virtual bool LoadFromINI(CCINIClass* pINI) override;
    virtual bool SaveToINI(CCINIClass* pINI) const override;

    // BuildingTypeClass_ToTile - the post-load pass over every registered
    // building type.  Each type's own section is queried for "ToTile" and the
    // name is resolved through IsometricTileTypeClass_FindIndex; a miss
    // leaves the stored pointer untouched.  Runs at the tail of
    // INIClass_ReadScenario.
    static void ToTile();

    // Second stage of the art load: the frames that need a theatre-specific
    // lookup (DeployingAnim, RoofDeployingAnim, DoorAnim, UnderDoorAnim,
    // UnderRoofDoorAnim, Rubble, SpecialZOverlay).
    void Load2DArt(int32 idxTheater);
    virtual AbstractType GetAbstractDerivationID() const override;
    virtual bool HasThisID(const char* pID) const override;
    virtual int32 GetCRC() const override;
    virtual int32 Size() const override;
    virtual AbstractType GetClassID() const override;
    virtual const char* get_ID() const override;
    virtual const wchar_t* GetUIName() const override;
    virtual void ComputeCRC(CRCEngine& crc) const override;

    // Building-specific helpers
    virtual bool IsUndeployable() const;
    virtual bool CanBeSold() const;
    virtual bool CanBeRepaired() const;
    virtual bool IsSimpleDeployer() const;
    virtual bool IsFirebase() const;
    virtual bool IsFactory() const;
    virtual bool IsPowerPlant() const;
    virtual bool IsWall() const;
    virtual bool IsTiberiumStorage() const;

    int32 Get_Width() const;
    int32 Get_Height() const;
    RectangleStruct Get_Occupy_Rect() const;
    int32 Get_Power_Output() const;
    int32 Get_Power_Drain() const;
    int32 Get_Storage_Capacity() const;
    AbstractType Get_Factory_Type() const;
    int32 Find_Exit_Cell(const CoordStruct& baseCoord) const;

    BuildingTypeClass() noexcept;
    explicit BuildingTypeClass(noinit_t) noexcept : TechnoTypeClass(noinit) {}

public:
    int32       BuildingFoundation; // Foundation width/height
    int32       Height;
    int32       Power;
    int32       PowerDrain;
    int32       Bib;
    bool        CanBeSold_;
    bool        IsUndeployable_;
    bool        IsSimpleDeployer_;
    bool        IsFirebase_;
    bool        IsFactory_;
    bool        HasSpotlight;
    bool        HasBib;
    bool        HasHelipad;
    bool        HasDock;
    bool        IsBase;
    bool        IsGate;
    bool        IsOreRefinery;
    bool        IsOreStorage;
    bool        IsWeaponsFactory;
    bool        IsBarracks;
    bool        IsRadar;
    bool        IsTech;
    bool        IsSecretLab;
    bool        IsConstructionYard;
    bool        IsAirport;
    bool        IsWarfactory;
    bool        IsNavalYard;
    bool        IsRepairPad;
    bool        IsMissileSilo;
    bool        IsPowered;
    bool        IsCanC4;
    bool        IsCanBeOccupied;
    bool        IsCanBeDriven;
    bool        IsCanBeCaptured;
    bool        IsCanBeRepaired_;
    bool        IsCanBeSold_;
    bool        IsCanBePowered;
    bool        IsCanBeDestroyed;
    bool        IsCanBeDamaged;
    bool        IsCanBeInfiltrated;
    bool        IsCanBeSpied;
    bool        IsCanBeSabotaged;
    bool        IsCanBeStolen;
    bool        IsCanBeHijacked;
    int32       Storage;
    int32       BuildingAnimCount;
    int32       OccupyCount;
    int32       NumberOfDocks;
    int32       Adjacent;
    int32       MaxWalls;
    int32       SuperWeapon;
    int32       SuperWeapon2;
    int32       WeaponCount;
    WeaponStruct Weapons[2];
    int32       OccupyWeaponCount;
    WeaponStruct OccupyWeapons[2];
    int32       EliteOccupyWeaponCount;
    WeaponStruct EliteOccupyWeapons[2];
    bool        HasSuperWeapon;
    bool        HasSuperWeapon2;
    bool        IsPlug;
    bool        IsDrain;
    bool        IsDrainable;
    bool        IsRig;
    bool        IsRigOwner;
    bool        IsResource;
    bool        IsResourceGatherer;
    bool        IsBombable;
    bool        IsAutoFire;
    bool        IsGuardRange;
    bool        IsAggressive;
    bool        IsUndeployableMember;
    bool        IsSellable;
    bool        IsRepairable;
    bool        IsUnsellable;
    bool        IsUngarrisonable;
    bool        IsNaval;
    bool        IsLand;
    bool        IsAir;
    bool        IsOrganic;
    bool        IsNeutral;
    bool        IsInfiltratable;
    bool        IsStealthy;
    bool        IsHealable;
    bool        IsTilter;
    bool        IsToProtect;
    bool        IsNominal;
    bool        IsRadarInvisible;
    bool        IsDontScore;
    bool        IsNoThreat;
    bool        IsSensorsSight;
    bool        IsHunterSeeker;
    bool        IsIvan;
    bool        IsLeader;
    bool        IsCarryall;
    bool        IsTrain;
    bool        IsConsideredAircraft;
    bool        IsConsideredVehicle;
    bool        IsPowered_;
    bool        IsScanner;
    bool        IsSensor;
    bool        IsDetector;
    bool        IsSensors;
    bool        IsPreventAttackMove;
    bool        IsNaval_;
    bool        IsLand_;
    bool        IsAir_;
    bool        IsOrganic_;
    bool        IsNeutral_;
    bool        IsInfiltratable_;
    bool        IsStealthy_;
    bool        IsHealable_;
    bool        IsTilter_;
    bool        IsToProtect_;
    bool        IsNominal_;
    bool        IsRadarInvisible_;
    bool        IsDontScore_;
    bool        IsNoThreat_;
    bool        IsSensorsSight_;
    bool        IsHunterSeeker_;
    bool        IsIvan_;
    bool        IsLeader_;
    bool        IsDock;
    bool        IsHelipad;
    bool        IsHasBib;
    bool        IsHasSpotlight;
    bool        IsBase_;
    bool        IsWall_;
    bool        IsGate_;
    bool        IsOreRefinery_;
    bool        IsOreStorage_;
    bool        IsWeaponsFactory_;
    bool        IsBarracks_;
    bool        IsRadar_;
    bool        IsTech_;
    bool        IsSecretLab_;
    bool        IsConstructionYard_;
    bool        IsAirport_;
    bool        IsWarfactory_;
    bool        IsNavalYard_;
    bool        IsRepairPad_;
    bool        IsMissileSilo_;
    bool        IsPlug_;
    bool        IsDrain_;
    bool        IsDrainable_;
    bool        IsRig_;
    bool        IsRigOwner_;
    bool        IsResource_;
    bool        IsResourceGatherer_;
    bool        IsBombable_;
    bool        IsAutoFire_;
    bool        IsGuardRange_;
    bool        IsAggressive_;
    bool        IsUndeployable__;
    bool        IsSellable_;
    bool        IsRepairable_;
    bool        IsUnsellable_;
    bool        IsUngarrisonable_;
    float       ThreatPosedValue_;
    int32       DeathWeaponIndex_;
    int32       BuildingAnimCount_;
    int32       OccupyCount_;
    int32       NumberOfDocks_;
    int32       Adjacent_;
    int32       MaxWalls_;
    bool        IsPowered2;
    bool        IsPlug2;
    bool        IsDrain2;
    bool        IsDrainable2;
    bool        IsRig2;
    bool        IsRigOwner2;
    bool        IsResource2;
    bool        IsResourceGatherer2;
    BYTE        padding_BuildingType[4];
    // ------------------------------------------------------------------
    // Rules / Art INI fields
    // ------------------------------------------------------------------
    BuildCat     BuildCatValue;
    int32        AntiInfantryValue;
    int32        AntiArmorValue;
    int32        AntiAirValue;
    int32        HalfDamageSmokeLocation1[3];
    int32        HalfDamageSmokeLocation2[3];
    bool         Radar;
    bool         SpySat;
    bool         WaterBound;
    bool         Capturable;
    bool         Powered;
    bool         PoweredSpecial;
    bool         Overpowerable;
    bool         Spyable;
    bool         CanC4;
    bool         WantsExtraSpace;
    bool         Unsellable;
    bool         ClickRepairable;
    bool         CanBeOccupied;
    bool         CanOccupyFire;
    bool         ShowOccupantPips;
    int32        MaxNumberOccupants;
    int32        NumberImpassableRows;
    int32        ProduceCashStartup;
    int32        ProduceCashAmount;
    int32        ProduceCashDelay;
    int32        InfantryGainSelfHeal;
    int32        UnitsGainSelfHeal;
    int32        RefinerySmokeFrames;
    bool         BaseNormal;
    bool         EligibileForAllyBuilding;
    bool         EligibleForDelayKill;
    bool         NeedsEngineer;
    bool         ProtectWithWall;
    bool         Wall;
    bool         Weeder;
    bool         Helipad;
    bool         OrePurifier;
    bool         FactoryPlant;
    UnitTypeClass* FreeUnit;
    bool         HoverPad;
    bool         IsTemple;
    InfantryTypeClass* SecretInfantry;
    UnitTypeClass* SecretUnit;
    double       InfantryCostBonus;
    double       UnitsCostBonus;
    double       AircraftCostBonus;
    double       BuildingsCostBonus;
    double       DefensesCostBonus;
    bool         TogglePower;
    int32 BuildupSound;
    int32 PackupSound;
    int32 CreateUnitSound;
    int32 UnitExitSound;
    int32 UnitEnterSound;
    int32 WorkingSound;
    int32 NotWorkingSound;
    bool         UnitRepair;
    bool         UnitReload;
    bool         Bunker;
    bool         Cloning;
    bool         Grinding;
    bool         UnitAbsorb;
    bool         InfantryAbsorb;
    bool         SecretLab;
    bool         DockUnload;
    bool         Gate;
    bool         SAM;
    bool         ConstructionYard;
    bool         NukeSilo;
    bool         Refinery;
    bool         WeaponsFactory;
    bool         LaserFencePost;
    bool         LaserFence;
    bool         FirestormWall;
    bool         Hospital;
    bool         Armory;
    bool         GDIBarracks;
    bool         NODBarracks;
    bool         YuriBarracks;
    bool         EMPulseCannon;
    bool         TickTank;
    double       ChargedAnimTime;
    bool         CloakGenerator;
    bool         SensorArray;
    int32        CloakRadiusInCells;
    int32        PsychicDetectionRadius;
    int32        BarrelStartPitch;
    int32        DeployFacing;
    int32        LightVisibility;
    double       LightIntensity;
    double       LightRedTint;
    double       LightGreenTint;
    double       LightBlueTint;
    double       GateCloseDelay;
    bool         InvisibleInGame;
    char        PowersUpBuilding[0x20];
    int32        PowersUpToLevel;
    bool         BridgeRepairHut;
    bool         HasStupidGuardMode;
    bool         CrateBeneath;
    bool         CrateBeneathIsMoney;
    bool         LeaveRubble;
    bool         PlaceAnywhere;
    bool         ICBMLauncher;
    bool         Artillary;
    int32        TargetCoordOffset[3];
    int32        ExitCoord[3];
    bool         AIBuildThis;
    bool         IsBaseDefense;
    bool         IsThreatRatingNode;
    bool         ConcentricRadialIndicator;
    int32        ExtraPower;
    int32        OccupyHeight;
    bool         Recoilless;
    bool         DoubleThick;
    bool         Flat;
    bool         SiloDamage;
    bool         ChargeAnim;
    bool         IsAnimDelayedFire;
    int32        DelayedFireDelay;
    OverlayTypeClass* ToOverlay;
    Foundation   FoundationValue;
    int32        MidPoint;
    int32        DoorStages;
    bool         DamagedDoor;
    bool         TerrainPalette;
    int32        GateStages;
    int32        PrimaryFirePixelOffset[2];
    int32        SecondaryFirePixelOffset[2];
    bool         PrimaryFireDualOffset;
    bool         ExtraDamageStage;
    int32        SpecialZOverlayZAdjust;
    int32        NormalZAdjust;
    int32        ZShapePointMove[2];
    int32        ExtraLight;
    bool         CanHideThings;
    int32        QueueingCell[2];
    char        Buildup[0x20];
    char        DeployingAnim[0x20];
    char        RoofDeployingAnim[0x20];
    char        DoorAnim[0x20];
    char        UnderDoorAnim[0x20];
    char        UnderRoofDoorAnim[0x20];
    char        Rubble[0x20];
    char        SpecialZOverlay[0x20];
    char        AnimIdle[0x20];
    char        AnimActive[0x20];
    char        AnimAux1[0x20];
    char        AnimAux2[0x20];
    char        ActiveAnim[0x20];
    char        ActiveAnimDamaged[0x20];
    char        ActiveAnimGarrisoned[0x20];
    int32        ActiveAnimX;
    int32        ActiveAnimY;
    int32        ActiveAnimZAdjust;
    int32        ActiveAnimYSort;
    bool         ActiveAnimPowered;
    bool         ActiveAnimPoweredLight;
    bool         ActiveAnimPoweredEffect;
    bool         ActiveAnimPoweredSpecial;
    char        ActiveAnimTwo[0x20];
    char        ActiveAnimTwoDamaged[0x20];
    char        ActiveAnimTwoGarrisoned[0x20];
    int32        ActiveAnimTwoX;
    int32        ActiveAnimTwoY;
    int32        ActiveAnimTwoZAdjust;
    int32        ActiveAnimTwoYSort;
    bool         ActiveAnimTwoPowered;
    bool         ActiveAnimTwoPoweredLight;
    bool         ActiveAnimTwoPoweredEffect;
    bool         ActiveAnimTwoPoweredSpecial;
    char        ActiveAnimThree[0x20];
    char        ActiveAnimThreeDamaged[0x20];
    char        ActiveAnimThreeGarrisoned[0x20];
    int32        ActiveAnimThreeX;
    int32        ActiveAnimThreeY;
    int32        ActiveAnimThreeZAdjust;
    int32        ActiveAnimThreeYSort;
    bool         ActiveAnimThreePowered;
    bool         ActiveAnimThreePoweredLight;
    bool         ActiveAnimThreePoweredEffect;
    bool         ActiveAnimThreePoweredSpecial;
    char        ActiveAnimFour[0x20];
    char        ActiveAnimFourDamaged[0x20];
    char        ActiveAnimFourGarrisoned[0x20];
    int32        ActiveAnimFourX;
    int32        ActiveAnimFourY;
    int32        ActiveAnimFourZAdjust;
    int32        ActiveAnimFourYSort;
    bool         ActiveAnimFourPowered;
    bool         ActiveAnimFourPoweredLight;
    bool         ActiveAnimFourPoweredEffect;
    bool         ActiveAnimFourPoweredSpecial;
    char        SuperAnim[0x20];
    char        SuperAnimDamaged[0x20];
    char        SuperAnimGarrisoned[0x20];
    int32        SuperAnimX;
    int32        SuperAnimY;
    int32        SuperAnimZAdjust;
    int32        SuperAnimYSort;
    bool         SuperAnimPowered;
    bool         SuperAnimPoweredLight;
    bool         SuperAnimPoweredEffect;
    bool         SuperAnimPoweredSpecial;
    char        SuperAnimTwo[0x20];
    char        SuperAnimTwoDamaged[0x20];
    char        SuperAnimTwoGarrisoned[0x20];
    int32        SuperAnimTwoX;
    int32        SuperAnimTwoY;
    int32        SuperAnimTwoZAdjust;
    int32        SuperAnimTwoYSort;
    bool         SuperAnimTwoPowered;
    bool         SuperAnimTwoPoweredLight;
    bool         SuperAnimTwoPoweredEffect;
    bool         SuperAnimTwoPoweredSpecial;
    char        SuperAnimThree[0x20];
    char        SuperAnimThreeDamaged[0x20];
    char        SuperAnimThreeGarrisoned[0x20];
    int32        SuperAnimThreeX;
    int32        SuperAnimThreeY;
    int32        SuperAnimThreeZAdjust;
    int32        SuperAnimThreeYSort;
    bool         SuperAnimThreePowered;
    bool         SuperAnimThreePoweredLight;
    bool         SuperAnimThreePoweredEffect;
    bool         SuperAnimThreePoweredSpecial;
    char        SuperAnimFour[0x20];
    char        SuperAnimFourDamaged[0x20];
    char        SuperAnimFourGarrisoned[0x20];
    int32        SuperAnimFourX;
    int32        SuperAnimFourY;
    int32        SuperAnimFourZAdjust;
    int32        SuperAnimFourYSort;
    bool         SuperAnimFourPowered;
    bool         SuperAnimFourPoweredLight;
    bool         SuperAnimFourPoweredEffect;
    bool         SuperAnimFourPoweredSpecial;
    char        SpecialAnim[0x20];
    char        SpecialAnimDamaged[0x20];
    char        SpecialAnimGarrisoned[0x20];
    int32        SpecialAnimX;
    int32        SpecialAnimY;
    int32        SpecialAnimZAdjust;
    int32        SpecialAnimYSort;
    bool         SpecialAnimPowered;
    bool         SpecialAnimPoweredLight;
    bool         SpecialAnimPoweredEffect;
    bool         SpecialAnimPoweredSpecial;
    char        SpecialAnimTwo[0x20];
    char        SpecialAnimTwoDamaged[0x20];
    char        SpecialAnimTwoGarrisoned[0x20];
    int32        SpecialAnimTwoX;
    int32        SpecialAnimTwoY;
    int32        SpecialAnimTwoZAdjust;
    int32        SpecialAnimTwoYSort;
    bool         SpecialAnimTwoPowered;
    bool         SpecialAnimTwoPoweredLight;
    bool         SpecialAnimTwoPoweredEffect;
    bool         SpecialAnimTwoPoweredSpecial;
    char        SpecialAnimThree[0x20];
    char        SpecialAnimThreeDamaged[0x20];
    char        SpecialAnimThreeGarrisoned[0x20];
    int32        SpecialAnimThreeX;
    int32        SpecialAnimThreeY;
    int32        SpecialAnimThreeZAdjust;
    int32        SpecialAnimThreeYSort;
    bool         SpecialAnimThreePowered;
    bool         SpecialAnimThreePoweredLight;
    bool         SpecialAnimThreePoweredEffect;
    bool         SpecialAnimThreePoweredSpecial;
    char        SpecialAnimFour[0x20];
    char        SpecialAnimFourDamaged[0x20];
    char        SpecialAnimFourGarrisoned[0x20];
    int32        SpecialAnimFourX;
    int32        SpecialAnimFourY;
    int32        SpecialAnimFourZAdjust;
    int32        SpecialAnimFourYSort;
    bool         SpecialAnimFourPowered;
    bool         SpecialAnimFourPoweredLight;
    bool         SpecialAnimFourPoweredEffect;
    bool         SpecialAnimFourPoweredSpecial;
    char        LowPower[0x20];
    char        LowPowerDamaged[0x20];
    char        LowPowerGarrisoned[0x20];
    int32        LowPowerX;
    int32        LowPowerY;
    int32        LowPowerZAdjust;
    int32        LowPowerYSort;
    bool         LowPowerPowered;
    bool         LowPowerPoweredLight;
    bool         LowPowerPoweredEffect;
    bool         LowPowerPoweredSpecial;
    char        SuperLowPower[0x20];
    char        SuperLowPowerDamaged[0x20];
    char        SuperLowPowerGarrisoned[0x20];
    int32        SuperLowPowerX;
    int32        SuperLowPowerY;
    int32        SuperLowPowerZAdjust;
    int32        SuperLowPowerYSort;
    bool         SuperLowPowerPowered;
    bool         SuperLowPowerPoweredLight;
    bool         SuperLowPowerPoweredEffect;
    bool         SuperLowPowerPoweredSpecial;
    char        ProductionAnim[0x20];
    char        ProductionAnimDamaged[0x20];
    char        ProductionAnimGarrisoned[0x20];
    int32        ProductionAnimX;
    int32        ProductionAnimY;
    int32        ProductionAnimZAdjust;
    int32        ProductionAnimYSort;
    char        IdleAnim[0x20];
    char        IdleAnimDamaged[0x20];
    char        IdleAnimGarrisoned[0x20];
    int32        IdleAnimX;
    int32        IdleAnimY;
    int32        IdleAnimZAdjust;
    int32        IdleAnimYSort;
    bool         IdleAnimPowered;
    bool         IdleAnimPoweredLight;
    bool         IdleAnimPoweredEffect;
    bool         IdleAnimPoweredSpecial;
    char        PreProductionAnim[0x20];
    char        PreProductionAnimDamaged[0x20];
    char        PreProductionAnimGarrisoned[0x20];
    int32        PreProductionAnimX;
    int32        PreProductionAnimY;
    int32        PreProductionAnimZAdjust;
    int32        PreProductionAnimYSort;
    char        TurretAnim[0x20];
    char        TurretAnimDamaged[0x20];
    char        TurretAnimGarrisoned[0x20];
    int32        TurretAnimX;
    int32        TurretAnimY;
    int32        TurretAnimZAdjust;
    int32        TurretAnimYSort;
    bool         TurretAnimIsVoxel;
    bool         BarrelAnimIsVoxel;
    char        VoxelBarrelFile[0x20];
    int32        VoxelBarrelOffsetToPitchPivotPoint[3];
    int32        VoxelBarrelOffsetToRotatePivotPoint[3];
    int32        VoxelBarrelOffsetToBuildingPivotPoint[3];
    int32        VoxelBarrelOffsetToBarrelEnd[3];
    int32        Upgrades;
    int32        AddOccupy[8][2];
    int32        RemoveOccupy[8][2];
    char        PowerUpAnim[4][0x10];
    char        PowerUpDamagedAnim[4][0x10];
    int32       PowerUpLocXX[4];
    int32       PowerUpLocYY[4];
    int32       PowerUpLocZZ[4];
    int32       PowerUpYSort[4];
    int32        DockingOffset[4][3];
    int32        MuzzleFlash;
    int32        DamageFireOffset[2];
    int32        CaptureEvaEvent;
    BuildingTypeClass* SecretBuilding;

    // "ToTile" - the tile set this building is drawn from, resolved by
    // BuildingTypeClass_ToTile after the rules are loaded.
    IsometricTileType* TileToUse;
};
