#pragma once

#include <Abstract/AbstractTypeClass.h>
#include <Abstract/ObjectTypeClass.h>
#include <Containers/DynamicVectorClass.h>
#include <Containers/VectorClass.h>

class CCINIClass;
class ConvertClass;
class CRCEngine;
class InfantryTypeClass;
class SHPStruct;

// ============================================================================
// TechnoTypeClass - base for all techno type definitions
// Inherits ObjectTypeClass
// ============================================================================
class NOVTABLE TechnoTypeClass : public ObjectTypeClass {
public:
    static const AbstractType AbsID = AbstractType::TechnoType;

    static DynamicVectorClass<TechnoTypeClass*>* Array;

    static TechnoTypeClass* Find(const char* pID);
    static TechnoTypeClass* FindByIndex(int32 index);
    static int32 GetCount();
    static void Init_Array();
    static void Delete_Array();
    static void Delete_All();

    virtual ~TechnoTypeClass();
    virtual bool LoadFromINI(CCINIClass* pINI) override;
    virtual bool SaveToINI(CCINIClass* pINI) const;
    virtual AbstractType GetAbstractDerivationID() const;
    virtual bool HasThisID(const char* pID) const;
    virtual int32 GetCRC() const;
    virtual int32 Size() const;
    virtual AbstractType GetClassID() const;
    virtual const char* get_ID() const;
    virtual const wchar_t* GetUIName() const;
    virtual bool IsBuildable() const;
    virtual bool IsTrainable() const;
    virtual bool IsSelectable() const;
    virtual bool IsLegalTarget() const;
    virtual bool IsImmune() const;
    virtual bool IsLegalDamsel() const;
    virtual bool IsInsignificant() const;

    virtual bool HasTurret() const;
    virtual bool CanCloak() const;
    virtual bool IsVoxel() const;
    virtual bool HasDeployer() const;
    virtual bool HasUndeployer() const;
    virtual bool HasFirewall() const;
    // TechnoTypeClass vtable slot "CanMobileAttack": whether the type is
    // allowed to fire while on the move.  FootClass::CanAttack forwards here.
    virtual bool CanMobileAttack() const;
    virtual int32 GetWeaponCount() const;
    virtual WeaponStruct* GetWeapon(int32 index) const;

    // Extended accessors used by the sidebar / AI
    virtual int32  Get_Max_Speed() const;
    virtual Armor  Get_Armor() const;
    virtual bool   Is_Two_Shooter() const;
    virtual int32  Get_Cameo_Index() const;
    virtual CoordStruct Get_Display_Coords() const;
    virtual bool   Is_Veteran() const;
    virtual bool   Is_Crewed() const;
    virtual void   Resolve_SHP_References() override;
    virtual Point2D Get_Image_Size() const;
    virtual AbstractType Get_Build_Queue_Type() const;

    virtual void ComputeCRC(CRCEngine& crc) const override;

    TechnoTypeClass() noexcept;

protected:
    explicit __forceinline TechnoTypeClass(noinit_t) noexcept : ObjectTypeClass(noinit_t{}) {}

public:
    int32       Speed;
    Armor       ArmorType;
    SpeedType   SpeedTypeVal;
    MovementZone MoveZone;
    AbstractType Factory;
    int32       ROT;
    int32       WeaponCount;
    WeaponStruct Weapons[18];
    bool        HasTurret_;
    bool        CanCloak_;
    bool        IsVoxel_;
    bool        HasDeployer_;
    bool        HasUndeployer_;
    bool        HasFirewall_;
    bool        IsBuildable_;
    bool        IsTrainable_;
    bool        HasPassengers;
    int32       Passengers;
    int32       OpenTopped;
    int32       SizeLimit;
    double      CloakSpeed;
    double      CloakRadius;
    int32       CrewCount;
    InfantryTypeClass* Crew;
    AbstractType CrewType;
    int32       Ammo;
    bool        NoAmmo;
    int32       OccupyWeaponCount;
    int32       OccupyWeaponRangeBonus;
    bool        IsHarvester;
    bool        IsWeeder;
    bool        IsResourceGatherer;
    bool        IsUndeployable;
    bool        IsBombable;
    bool        IsAutoFire;
    bool        IsGuardRange;
    bool        IsAggressive;
    bool        IsSelectable_;
    bool        IsInsignificant_;
    bool        IsLegalTarget_;
    bool        IsImmune_;
    bool        IsLegalDamsel_;
    bool        IsUnsellable;
    bool        IsRepairable;
    bool        IsSellable;
    bool        IsPowered;
    bool        IsScanner;
    bool        IsSensor;
    bool        IsDetector;
    bool        IsSensors;
    bool        IsPreventAttackMove;
    bool        IsNaval;
    bool        IsLand;
    bool        IsAir;
    bool        IsOrganic;
    bool        IsNeutral;
    bool        IsInfiltratable;
    bool        IsStealthy;
    bool        IsHealable;
    bool        IsSelectable_old;
    bool        IsTilter;
    bool        IsToProtect;
    bool        IsNominal;
    bool        IsRadarInvisible;
    bool        IsDontScore;
    bool        IsNoThreat;
    bool        IsSensorsSight;
    bool        IsHunterSeeker;
    bool        IsIvan;
    bool        IsLeader;
    bool        IsCarryall;
    bool        IsTrain;
    bool        IsConsideredAircraft;
    bool        IsConsideredVehicle;
    bool        IsSimpleDeployer;
    bool        IsFirebase;
    bool        IsSonic;
    bool        IsVan;
    bool        IsBalloonHover;
    bool        IsCyborg;
    bool        IsNotHuman;
    bool        IsImmuneToPsionics;
    bool        IsImmuneToPoison;
    bool        IsImmuneToRadiation;
    bool        IsImmuneToBerserk;
    bool        IsImmuneToEMP;
    bool        IsCrushable;
    bool        IsCrushable2;
    bool        IsTeleporter;
    bool        IsChrono;
    bool        IsBomb;
    bool        IsCow;
    bool        IsDog;
    bool        IsBoris;
    bool        IsArmed;
    bool        IsMissileSpawn;
    float       ThreatPosedValue;
    int32       DeathWeaponIndex;
    int32       WeaponCharge;
    bool        IsFake;
    bool        IsDisableable;
    bool        IsCanBeSuppressed;
    bool        IsCanBeOccupied;
    bool        IsCanBeDriven;
    bool        IsCanBeCaptured;
    bool        IsCanBeRepaired;
    bool        IsCanBeSold;
    bool        IsCanBePowered;
    bool        IsCanBeDestroyed;
    bool        IsCanBeDamaged;
    bool        IsCanBeInfiltrated;
    bool        IsCanBeSpied;
    bool        IsCanBeSabotaged;
    bool        IsCanBeStolen;
    bool        IsCanBeHijacked;

    // These are actually used by subclasses
    bool        Deployer;
    bool        Undeployer;
    bool        Firewall;
    bool        Turret;
    bool        Cloak;
    bool        Voxel;

    // ------------------------------------------------------------------
    // Additional fields populated by LoadFromINI
    // ------------------------------------------------------------------
    int32       SightRange;
    int32       GuardRange;
    int32       Strength;
    int32       BuildCost;
    int32       BuildTime;
    int32       RepairCost;
    int32       RefundPercent;
    int32       VeteranAbilities[4];
    int32       EliteAbilities[4];
    int32       VeteranRatio;
    int32       InitialVeterancy;
    int32       TurretROT;
    int32       IdleTimer;
    bool        IsCrewed_;
    char        Cameo[0x20];
    char        ImageFile[0x20];
    SHPStruct*  CameoShape;
    SHPStruct*  ImageShape;
    Point2D     ImageSize;
    // ------------------------------------------------------------------
    // Rules / Art INI fields
    // ------------------------------------------------------------------
    int32        LandTargeting;
    int32        NavalTargeting;
    SpeedType    SpeedTypeValue;
    bool         CanBeHidden;
    bool         TypeImmune;
    int32        WalkRate;
    int32        IdleRate;
    bool         MoveToShroud;
    bool         DoubleOwned;
    bool         Explodes;
    WeaponTypeClass* DeathWeapon;
    double       DeathWeaponDamageModifier;
    int32        FlightLevel;
    bool         IsDropship;
    double       PitchAngle;
    double       RollAngle;
    double       PitchSpeed;
    char        Locomotor[0x20];
    int32        CloakingSpeed;
    double       ThreatAvoidanceCoefficient;
    int32        SlowdownDistance;
    double       DeaccelerationFactor;
    double       AccelerationFactor;
    double       Weight;
    double       PhysicalSize;
    double       SizeValue;
    bool         HoverAttack;
    VHPScan      VHPScanValue;
    int32        MaxDebris;
    int32        MinDebris;
    char        DebrisTypes[0x20];
    int32       DebrisMaximums[32];
    char        DebrisAnims[0x20];
    bool         HasTurretTooltips;
    int32        TurretCount;
    bool         IsChargeTurret;
    bool         ClearAllWeapons;
    WeaponTypeClass* Primary;
    WeaponTypeClass* Secondary;
    WeaponTypeClass* ElitePrimary;
    WeaponTypeClass* EliteSecondary;
    char        VoiceMove[0x100];
    char        VoiceSelect[0x100];
    char        VoiceSelectEnslaved[0x100];
    char        VoiceSelectDeactivated[0x100];
    char        VoiceAttack[0x100];
    char        VoiceSpecialAttack[0x100];
    char        VoiceDie[0x100];
    char        VoiceFeedback[0x100];
    int32 AuxSound1;
    int32 AuxSound2;
    int32 CreateSound;
    int32 DamageSound;
    int32 ImpactWaterSound;
    int32 ImpactLandSound;
    int32 CrashingSound;
    int32 SinkingSound;
    int32 VoiceFalling;
    int32 VoiceCrashing;
    int32 VoiceSinking;
    int32 VoiceEnter;
    int32 VoiceCapture;
    bool         CloakStop;
    int32        Storage;
    int32        BuildLimit;
    Category     CategoryValue;
    // 根据游戏行为，可知 Dock 是一份"可停靠建筑类型"的列表，而不是单一指针：
    // 规则文件里该键写成以逗号分隔的多个建筑名，每一项都要单独解析并追加进
    // 列表；载具/飞机在执行进入建筑、返回维修或装弹时，会遍历这份列表来挑选
    // 最近且允许停靠的目标。故此处按列表建模。
    VectorClass<BuildingTypeClass*> Dock;
    BuildingTypeClass* DeploysInto;
    UnitTypeClass* UndeploysInto;
    UnitTypeClass* PowersUnit;
    bool         PoweredUnit;
    bool         LightningRod;
    bool         ManualReload;
    bool         TurretSpins;
    bool         TiltCrashJumpjet;
    int32 TurretRotateSound;
    int32 EnterTransportSound;
    int32 LeaveTransportSound;
    char        MoveSound[0x100];
    char        DieSound[0x100];
    int32 DeploySound;
    int32 UndeploySound;
    int32 ChronoInSound;
    int32 ChronoOutSound;
    int32 VoiceHarvest;
    int32 VoicePrimaryWeaponAttack;
    int32 VoicePrimaryEliteWeaponAttack;
    int32 VoiceSecondaryWeaponAttack;
    int32 VoiceSecondaryEliteWeaponAttack;
    int32 VoiceDeploy;
    int32 VoiceUndeploy;
    int32 EnterGrinderSound;
    int32 LeaveGrinderSound;
    int32 EnterBioReactorSound;
    int32 LeaveBioReactorSound;
    int32 ActivateSound;
    int32 DeactivateSound;
    int32 MindClearedSound;
    AnimTypeClass* Explosion;
    AnimTypeClass* DestroyAnim;
    ParticleSystemTypeClass* NaturalParticleSystem;
    ParticleSystemTypeClass* RefinerySmokeParticleSystem;
    char        DamageParticleSystems[0x20];
    char        DestroyParticleSystems[0x20];
    bool         DamSmkOffScrnRel;
    bool         Nominal;
    bool         DontScore;
    bool         DamageSelf;
    bool         Cloakable;
    bool         GapGenerator;
    int32        GapRadiusInCells;
    int32        SuperGapRadiusInCells;
    bool         Teleporter;
    bool         Sensors;
    bool         IsGattling;
    int32        WeaponStages;
    int32        RateUp;
    int32        RateDown;
    PipScale     PipScaleValue;
    bool         PipsDrawForAll;
    int32        LeptonMindControlOffset;
    int32        PixelSelectionBracketDelta;
    int32        PipWrap;
    int32        Sight;
    bool         ReselectIfLimboed;
    bool         RejoinTeamIfLimboed;
    int32        SensorsSight;
    int32        DetectDisguiseRange;
    int32        BombSight;
    int32        LeadershipRating;
    int32        MindControlRingOffset;
    double       BuildTimeMultiplier;
    bool         RevealToAll;
    bool         Drainable;
    bool         ResourceGatherer;
    bool         ResourceDestination;
    bool         CanDisguise;
    bool         PermaDisguise;
    bool         DetectDisguise;
    bool         DisguiseWhenStill;
    bool         CanPassiveAquire;
    bool         CanRetaliate;
    bool         CanApproachTarget;
    bool         CanRecalcApproachTarget;
    bool         RequiresStolenThirdTech;
    bool         RequiresStolenSovietTech;
    bool         RequiresStolenAlliedTech;
    int32        RequiredHouses;
    int32        SecretHouses;
    int32        ForbiddenHouses;
    int32        TechLevel;
    int32        AirstrikeTeam;
    int32        EliteAirstrikeTeam;
    AircraftTypeClass* AirstrikeTeamType;
    AircraftTypeClass* EliteAirstrikeTeamType;
    int32        AirstrikeRechargeTime;
    int32        EliteAirstrikeRechargeTime;
    int32        Cost;
    int32        Soylent;
    UnitTypeClass* UnloadingClass;
    AnimTypeClass* DeployingAnim;
    int32        InitialAmmo;
    int32        IFVMode;
    int32        RadialFireSegments;
    int32        DeployFireWeapon;
    bool         DeployFire;
    bool         DeployToLand;
    bool         MobileFire;
    bool         OpportunityFire;
    bool         DistributedFire;
    int32        Reload;
    int32        EmptyReload;
    int32        ReloadIncrement;
    bool         DamageReducesReadiness;
    double       ReadinessReductionMultiplier;
    bool         BerserkFriendly;
    bool         SprayAttack;
    bool         Pushy;
    bool         Natural;
    bool         Unnatural;
    bool         CloseRange;
    bool         PreventAttackMove;
    int32        Points;
    int32        ThreatPosed;
    int32        Owner;
    int32        AIBasePlanningSide;
    bool         Trainable;
    bool         Crewed;
    bool         Gunner;
    bool         Naval;
    bool         Repairable;
    bool         Invisible;
    bool         RadarVisible;
    bool         SelfHealing;
    bool         NoAutoFire;
    int32        FireAngle;
    double       DeployTime;
    int32        UndeployDelay;
    bool         Disableable;
    bool         ToProtect;
    bool         TiberiumHeal;
    bool         ImmuneToVeins;
    bool         AllowedToStartInMultiplayer;
    bool         StupidHunt;
    bool         TargetLaser;
    bool         HunterSeeker;
    bool         Crusher;
    bool         OmniCrusher;
    bool         OmniCrushResistant;
    // TechnoTypeClass+0x[Uncrushable]: the art declares the unit can never be
    // crushed even by an omni-crusher.
    bool         Uncrushable;
    bool         AutoCrush;
    bool         ImmuneToRadiation;
    bool         Underwater;
    bool         BalloonHover;
    bool         Slaved;
    int32        SlaveRegenRate;
    int32        SlavesNumber;
    int32        SlaveReloadRate;
    int32        OpenTransportWeapon;
    bool         Spawned;
    int32        SpawnRegenRate;
    int32        SpawnsNumber;
    int32        SpawnReloadRate;
    bool         MissileSpawn;
    bool         DefaultToGuardArea;
    bool         Warpable;
    bool         Parasiteable;
    bool         ImmuneToPsionics;
    bool         ImmuneToPsionicWeapons;
    bool         ConsideredAircraft;
    bool         Bunkerable;
    bool         Organic;
    bool         ImmuneToPoison;
    int32        SuppressionThreshold;
    bool         NoShadow;
    int32        JumpjetTurnRate;
    int32        JumpjetSpeed;
    double       JumpjetClimb;
    double       JumpjetCrash;
    int32        JumpjetHeight;
    double       JumpjetAccel;
    double       JumpjetWobbles;
    bool         JumpjetNoWobbles;
    int32        JumpjetDeviation;
    bool         JumpJet;
    bool         Crashable;
    bool         AttackFriendlies;
    bool         AttackCursorOnFriendlies;
    bool         TurretRecoil;
    int32        TurretTravel;
    int32        TurretCompressFrames;
    int32        TurretHoldFrames;
    int32        TurretRecoverFrames;
    int32        BarrelTravel;
    int32        BarrelCompressFrames;
    int32        BarrelHoldFrames;
    int32        BarrelRecoverFrames;
    bool         TiltsWhenCrushes;
    bool         Accelerates;
    int32        ZFudgeCliff;
    int32        ZFudgeColumn;
    int32        ZFudgeTunnel;
    int32        ZFudgeBridge;
    double       MyEffectivenessCoefficient;
    double       TargetEffectivenessCoefficient;
    double       TargetSpecialThreatCoefficient;
    double       TargetStrengthCoefficient;
    double       TargetDistanceCoefficient;
    double       SpecialThreatValue;
    bool         IsSelectableCombatant;
    bool         UseBuffer;
    char        Palette[0x20];
    int32        TurretOffset;
    int32        RotCount;
    bool         Remapable;
    bool         Normalized;
    bool         VisibleLoad;
    int32        ShadowIndex;
    bool         DisableVoxelCache;
    bool         DisableShadowCache;
    char        AltCameo[0x20];
    int32        PBarrelLength;
    int32        PBarrelThickness;
    int32        SecondaryFireFLH[3];
    int32        SBarrelLength;
    int32        ElitePBarrelLength;
    int32        ElitePBarrelThickness;
    int32        EliteSecondaryFireFLH[3];
    int32        EliteSBarrelLength;
    int32        EliteSBarrelThickness;
    bool         TurretNotExportedOnGround;
    int32        SecondSpawnOffset[3];
    MovementZone MovementZoneValue;
    char        EliteWeapon[10][0x20];
    int32        EliteStage[10];
    char        Weapon[18][0x20];
    int32        WeaponStage[10];
    int32        WeaponFLH[18][3];
    int32        WeaponBarrelLength[18];
    int32        WeaponBarrelThickness[18];
    bool         WeaponTurretLocked[18];
    int32        AlternateFLH[8][3];
    int32        AirRangeBonus;
    AircraftTypeClass* Spawns;
    InfantryTypeClass* Enslaves;
    int32        NaturalParticleLocation[3];
    int32        DamageSmokeOffset[3];
    int32        DestroySmokeOffset[3];
    int32        RefinerySmokeOffset[4][3];
    DynamicVectorClass<int32> Prerequisite;
    DynamicVectorClass<int32> PrerequisiteOverride;
    // ------------------------------------------------------------------------
    // 根据游戏行为，可知类型层还提供修复步长/飞行高度/炮塔识别等读取器，
    // 以及调色板与炮塔体素美术的装载入口；调色板转换器与炮塔美术槽位
    // 跟随类型对象生命周期。
    // ------------------------------------------------------------------------
    virtual int32  GetRepairStep() const;
    virtual int32  GetRepairStepCost() const;
    virtual int32  GetFlightLevel() const;
    virtual bool   DoesNotBurst() const;
    virtual bool   IsTurretChanger() const;
    virtual bool   CanAttackOnTheMove() const;
    virtual int32  GetDestinationTab(int32 kind, int32 sub) const;
    virtual void   GetParticleSysPos(CoordStruct& out) const;
    virtual void   ResetPos(CoordStruct& out) const;
    virtual void   ResetPosLeptons(CoordStruct& out) const;
    virtual void   UpdatePalette();
    static  void   ReplacePalette();
    virtual void   LoadTurretArt(const char* pImageName, int32 idx);
    virtual void   UnloadTurretArt();

    ConvertClass* PaletteConvert = nullptr;   // 按 Palette 文件名构建的调色板转换器
    struct TurretArtEntry { void* VXL; void* HVA; char VXLName[0x20]; char HVAName[0x20]; };
    TurretArtEntry Turrets[18] = {};     // 每个炮塔槽位的体素/动画句柄与文件名

};
